# Generated by Django 4.0.4 on 2022-05-13 06:10

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInstaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('settings', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='InstaPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_pk', models.IntegerField()),
                ('status', models.CharField(choices=[('pub', 'published'), ('drf', 'draft')], max_length=10)),
                ('page_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.myinstapage')),
            ],
        ),
    ]
